Repository opensearch-project/query-insights, pull requests merged in 2024-09, with the labels that each got.

#66 Query grouping framework for Top N queries and group by query similarity
  src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/QueryShapeGenerator.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/SearchQueryAggregationCategorizer.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/SearchQueryCategorizer.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/SearchQueryCategorizingVisitor.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/SearchQueryCounters.java
  src/main/java/org/opensearch/plugin/insights/core/service/grouper/MinMaxHeapQueryGrouper.java
  src/main/java/org/opensearch/plugin/insights/core/service/grouper/QueryGrouper.java
  src/main/java/org/opensearch/plugin/insights/rules/model/AggregationType.java
  src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  src/main/java/org/opensearch/plugin/insights/rules/model/GroupingType.java
  src/main/java/org/opensearch/plugin/insights/rules/model/Measurement.java
  src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
  src/test/java/org/opensearch/plugin/insights/core/service/grouper/MinMaxHeapQueryGrouperTests.java
  src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
Labels: backport 2.x

#87 [Backport 2.x] Add more integ tests for query insights
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/test/java/org/opensearch/plugin/insights/QueryInsightsRestTestCase.java
  src/test/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterIT.java
  src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/TopQueriesRestIT.java
Labels: backport 2.17

#90 Add configuration for publishing snapshot
  .github/workflows/maven-publish.yml
  build.gradle
Labels: backport 2.x, backport 2.17

#91 Add release notes for 2.17
  release-notes/opensearch-query-insights.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#92 [Backport 2.x] Add configuration for publishing snapshot (#90)
  .github/workflows/maven-publish.yml
  build.gradle
Labels: backport 2.17

#89 Add additional grouping ITs and refactor
  src/test/java/org/opensearch/plugin/insights/QueryInsightsRestTestCase.java
  src/test/java/org/opensearch/plugin/insights/core/service/grouper/MinMaxQueryGrouperByNoneIT.java
  src/test/java/org/opensearch/plugin/insights/core/service/grouper/MinMaxQueryGrouperBySimilarityIT.java
  src/test/java/org/opensearch/plugin/insights/core/service/grouper/MinMaxQueryGrouperIT.java
  src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/TopQueriesRestIT.java
Labels: backport 2.x, backport 2.17

#100 Update release notes with Grouping ITs
  release-notes/opensearch-query-insights.release-notes-2.17.0.0.md
Labels: backport 2.x, backport 2.17

#113 Use separate targets for security enabled tests
  build.gradle
Labels: backport 2.x, backport 2.17

#112 Refactor parsing logic for Measurement
  src/main/java/org/opensearch/plugin/insights/core/reader/LocalIndexReader.java
  src/main/java/org/opensearch/plugin/insights/rules/model/Measurement.java
  src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
  src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
Labels: backport 2.x

#117 Upgrade deprecated actions/upload-artifact versions to v4
  .github/workflows/ci.yml
  .github/workflows/integ-tests-with-security.yml
Labels: backport 2.x

#111 Refactor query shape field data maps
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/QueryShapeGenerator.java
  src/main/java/org/opensearch/plugin/insights/core/service/categorizer/QueryShapeVisitor.java
Labels: backport 2.x
