Repository opensearch-project/query-insights, pull requests merged in 2025-03, with the labels that each got.

#257 Change local index replica count to 0
  src/main/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporter.java
Labels: backport 2.x

#262 Use ClusterStateRequest with index pattern when searching for expired local indices
  src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
Labels: backport 2.x

#263 [Backport 2.x] Use ClusterStateRequest with index pattern when searching for expired local indices
  src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
Labels: backport 2.19

#266 Add strict hash check on top queries indices
  src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  src/test/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporterTests.java
  src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
Labels: backport 2.x

#279 Update Alpha1 to alpha1 in the release notes of 3.0.0.0-alpha1
  release-notes/opensearch-query-insights.release-notes-3.0.0.0-alpha1.md
Labels: v3.0.0, release

#282 Reduce MAX_TOP_N_INDEX_READ_SIZE to 50, sort by desc latency (#281)
  src/main/java/org/opensearch/plugin/insights/core/reader/LocalIndexReader.java
Labels: backport 2.19
